// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovCxbsI84elHt9LhXlK3EbQjl_xLrTwI',
    appId: '1:43229610735:web:a9336747a826bb7ef4111a',
    messagingSenderId: '43229610735',
    projectId: 'bookfeed-97956',
    authDomain: 'bookfeed-97956.firebaseapp.com',
    storageBucket: 'bookfeed-97956.firebasestorage.app',
    measurementId: 'G-Q2RXB075SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMPoaiaW6G56y2M4u_MakHyKiizjZSVc',
    appId: '1:43229610735:android:30083cfdf09498c7f4111a',
    messagingSenderId: '43229610735',
    projectId: 'bookfeed-97956',
    storageBucket: 'bookfeed-97956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPRNqa7ywBVHPgM3SkTj0DYGEzOAp-tI',
    appId: '1:43229610735:ios:4db9e23af266a95cf4111a',
    messagingSenderId: '43229610735',
    projectId: 'bookfeed-97956',
    storageBucket: 'bookfeed-97956.firebasestorage.app',
    iosBundleId: 'com.example.bookfeedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPRNqa7ywBVHPgM3SkTj0DYGEzOAp-tI',
    appId: '1:43229610735:ios:4db9e23af266a95cf4111a',
    messagingSenderId: '43229610735',
    projectId: 'bookfeed-97956',
    storageBucket: 'bookfeed-97956.firebasestorage.app',
    iosBundleId: 'com.example.bookfeedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCovCxbsI84elHt9LhXlK3EbQjl_xLrTwI',
    appId: '1:43229610735:web:560ac2bd4d5c954af4111a',
    messagingSenderId: '43229610735',
    projectId: 'bookfeed-97956',
    authDomain: 'bookfeed-97956.firebaseapp.com',
    storageBucket: 'bookfeed-97956.firebasestorage.app',
    measurementId: 'G-24T7HMRE66',
  );

}